# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Personal Site Info
title: Your Name
email: "name [at] mail [dot] com"
description: >- # this means to ignore newlines until "baseurl:"
  Personal Portfolio Website
domain: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: "Your Name"


# Social Media
github_url: "https://github.com"
linkedin_url: "https://www.linkedin.com"
youtube_url: "https://www.youtube.com"
spotify_url: "https://www.spotify.com"
soundcloud_url: "https://www.soundcloud.com"
twitter_username: 
github_username: 


# Location
city: "City"
state: "State"
country: "Country"


# School
university: "University of Example"
gradYear: "YYYY"
degree: "Bachelor of Science in Example"


# Build settings
#theme: minima
plugins:
  - jekyll-feed

# Default Variables
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      # values
      layout: "project"
      permalink: "/projects/:title"
      link: "Github.com"
      desc: "Project Description"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
